### PR TITLE
Adding TVL adapter for Levana Finance

### PR DESCRIPTION
**Pull request by lvn-savvy-dragon**
Opening as a draft, still waiting on copy for Methodology

### CODE REVIEW

**Comment by lvn-savvy-dragon** [comment]
@lvn-rusty-dragon Running the test outputs

```
--- osmosis ---
ATOM                      1.55 M
axlWBTC                   178.91 k
OSMO                      155.29 k
axlWETH                   95.68 k
SEI                       15.31 k
Total: 2.00 M 

--- sei ---
WETH                      47.58 k
SEI                       31.00 k
Total: 78.59 k 

--- tvl ---
ATOM                      1.55 M
axlWBTC                   178.91 k
OSMO                      155.29 k
axlWETH                   95.68 k
WETH                      47.58 k
SEI                       46.31 k
Total: 2.08 M 

------ TVL ------
osmosis                   2.00 M
sei                       78.59 k

total                    2.08 M 
```

Do these numbers look correct?

**Comment by lvn-rusty-dragon** [comment]
I'm not sure, what units are these supposed to be in?

**Comment by lvn-savvy-dragon** [comment]
USD, I spot checked a couple and they looked accurate but I'd like a second pair of eyes on it.

**Comment by lvn-rusty-dragon** [comment]
Yes, if those are USD numbers they look accurate to me too.

**Comment by lvn-savvy-dragon** [comment]
@lvn-rusty-dragon I updated the methodology, it's ready for review

**Review by lvn-rusty-dragon — APPROVED** [review]

**Pull request merged**
